apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: predictmyfuture
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: predictmyfuture.azurecr.io/server:latest
          imagePullPolicy: Always